### PR TITLE
fix  Cant add this to a CSVec

### PR DESCRIPTION
**Pull request by BelhalK**
This fix makes sure the object `summed` can be added to the object `self.workerSketches[0]`. 

Otherwise `isinstance(other, CSVec)` returns false.

### CODE REVIEW

**Comment by dhroth** [comment]
Thanks. The += in _sketchHelper() also needed to be changed, but I've pushed a fix. I've also pushed a few new features

**Comment by BelhalK** [comment]
Hi there. I don't see the difference in the function `_sketchHelperShortcut` with what I've PR here. 
Can you explain?

**Comment by dhroth** [comment]
Your PR had the correct change for that function, but the same change also needed to be made in _sketchHelper() in order to bring this repo up to date with the csh repo. Also your pull request added a .pyc binary file, which I would've had to make another commit to get rid of, so it was just easier to commit the complete fix myself

**Comment by BelhalK** [comment]
I understand. That's not how PR work though.
Understand that a contributor's PR does not necessarily fix all the bugs.
Yet, when the aforementioned fix is correct, it is the duty of the repo owner to merge it and then, only then, fix the other bugs he/she detected.
Otherwise, you may see how all repo owners would just copy PR's fix and do it themselves.
It's a bit dishonnest and not at all the common practice.

**Comment by dhroth** [comment]
I certainly wouldn't want to claim credit for your contributions to this repo, but the one-line change in your commit here is exactly what I said to do in the issue thread, except I said to make the same change on multiple lines and you only made it on one line. I don't think that I'm being "dishonest" or "copying" your PR when in fact, your pull request implements my suggested fix verbatim. Given that it wasn't your fix, it's a single-line change, and you only made the necessary change on one of three broken lines, I didn't see a problem with pushing the correct fix myself, especially given that I discovered I already had the necessary changes locally from a while ago, and I just hadn't gotten around to committing and pushing them yet.

**Pull request closed without merging**
